name: github_client
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_appauth: ^6.0.2
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.2
  url_launcher: ^6.2.6
  graphql_flutter: ^5.1.2
  flutter_web_auth_2: ^3.0.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
cupertino_icons: ^1.0.8

